[package]
name = "tokn-router"
version.workspace = true
edition.workspace = true
description = "Routing, relay, and proxy orchestration across providers for tokn gateway"
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
tokn-core = { workspace = true }
tokn-events = { workspace = true }
tokn-policy = { workspace = true }
tokn-accounts = { workspace = true }
tokn-access = { workspace = true }
tokn-headers = { workspace = true }
tokn-requests = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
bytes = { workspace = true }
flate2 = { workspace = true }
futures-util = { workspace = true }
http = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true, features = ["client-proxy"] }
parking_lot = { workspace = true }
rcgen = { workspace = true }
reqwest = { workspace = true }
rustls-native-certs = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
smol_str = { workspace = true }
snafu = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
tracing = { workspace = true }
time = { workspace = true }
zstd = { workspace = true }

[dev-dependencies]
tempfile = "3"
tokn-config = { workspace = true }
tokn-mock-server = { workspace = true }
tokn-persistence = { workspace = true }
toml = { workspace = true }
