//! Request-scoped publication for the public gateway lifecycle contract.
//!
//! The lifecycle is deliberately non-cloneable. Awaited boundary publication
//! takes `&mut self`, so the request-local sequence and bounded ingress order
//! cannot drift apart. A response or tunnel body owns the same value through
//! completion; dropping it submits the cancellation fallback registered with
//! [`Publisher::begin_guarded`].

use std::collections::BTreeMap;
use std::fmt;
use std::sync::{Arc, Mutex, MutexGuard};
use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};

use thiserror::Error;
use tokn_events::{
  AttemptFinished, AttemptNo, AttemptOutcome, AttemptUsage, BodyCapture, BodyFinished, BodyLeg, BodyProgress,
  BodyResult, CaptureOmission, ConnectClosed, ConnectReady, GatewayEvent, HubFailure, PublishError, Publisher,
  RequestFinished, RequestId, RequestOutcome, RequestPhase, RequestStarted, TerminalBatch, TerminalContext,
  TerminalGuard, TerminalRegistrationError, TerminalSubmitError, TrafficEvent, TrafficEventKind, TryPublishError,
};

/// Generates a gateway-owned request identity.
///
/// Client-provided request ids belong in [`tokn_events::Correlation`]. They
/// must not be passed through as persistence primary keys.
#[must_use]
pub fn generate_request_id() -> RequestId {
  RequestId::new(uuid::Uuid::new_v4().hyphenated().to_string())
    .expect("hyphenated UUIDs always satisfy the request ID grammar")
}

/// Process-level entry point for request lifecycle publication.
///
/// `disabled` is an intentional library mode, not a fake event hub. It keeps
/// the same request API while avoiding dispatcher and consumer setup.
#[derive(Clone, Debug, Default)]
pub struct RequestLifecycleEmitter {
  publisher: Option<Publisher<GatewayEvent>>,
}

impl RequestLifecycleEmitter {
  #[must_use]
  pub fn new(publisher: Publisher<GatewayEvent>) -> Self {
    Self {
      publisher: Some(publisher),
    }
  }

  #[must_use]
  pub const fn disabled() -> Self {
    Self { publisher: None }
  }

  #[must_use]
  pub const fn is_enabled(&self) -> bool {
    self.publisher.is_some()
  }

  /// Starts a lifecycle with a fresh gateway-generated identity.
  pub async fn begin(
    &self,
    started: RequestStarted,
  ) -> Result<RequestLifecycle, TerminalRegistrationError<GatewayEvent>> {
    self.begin_with_id(generate_request_id(), started).await
  }

  /// Starts a lifecycle with an identity generated by this crate.
  ///
  /// The `Started` event is admitted together with its terminal obligation
  /// before this method returns. Callers should invoke this before polling or
  /// parsing the request body.
  async fn begin_with_id(
    &self,
    request_id: RequestId,
    started: RequestStarted,
  ) -> Result<RequestLifecycle, TerminalRegistrationError<GatewayEvent>> {
    let clock = LifecycleClock::now();
    let shared = Arc::new(SharedLifecycle::new(request_id, clock.started_at));
    let started_event = shared.envelope(
      1,
      clock.started_at,
      clock.started_at_system_time,
      TrafficEventKind::Started(started),
    );
    let terminal = match &self.publisher {
      Some(publisher) => {
        let fallback = Arc::clone(&shared);
        Some(
          publisher
            .begin_guarded(started_event, move |context| fallback.materialize_terminal(context))
            .await?,
        )
      }
      None => None,
    };

    Ok(RequestLifecycle {
      publisher: self.publisher.clone(),
      terminal,
      shared,
    })
  }
}

/// Whether one lifecycle observation was sent or intentionally suppressed.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum LifecycleDelivery {
  Published,
  Disabled,
}

/// Result of a nonblocking body-progress publication.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ProgressPublication {
  Published,
  Disabled,
  /// The bounded ingress was full. The original cumulative fact is returned
  /// so a body wrapper can retry or merge it with its next update.
  Coalesce(BodyProgress),
}

/// A reliable boundary could not be admitted.
#[derive(Debug, Error)]
pub enum BoundaryPublishError {
  #[error("Started, Finished, and BodyProgress are owned by dedicated lifecycle methods")]
  DedicatedKind(TrafficEventKind),
  #[error(transparent)]
  Delivery(#[from] PublishError<GatewayEvent>),
}

impl BoundaryPublishError {
  #[must_use]
  pub fn into_kind(self) -> TrafficEventKind {
    match self {
      Self::DedicatedKind(kind) => kind,
      Self::Delivery(error) => gateway_event_kind(error.into_event()),
    }
  }
}

/// A progress observation could no longer use its guarded lifecycle.
#[derive(Debug, Error)]
pub enum ProgressPublishError {
  #[error("event hub is closed")]
  Closed(BodyProgress),
  #[error("event hub failed: {failure}")]
  Failed {
    progress: BodyProgress,
    #[source]
    failure: Arc<HubFailure>,
  },
}

impl ProgressPublishError {
  #[must_use]
  pub fn into_progress(self) -> BodyProgress {
    match self {
      Self::Closed(progress) | Self::Failed { progress, .. } => progress,
    }
  }
}

/// Request completion fields whose attempt count is owned by the lifecycle.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RequestCompletion {
  pub outcome: RequestOutcome,
  pub phase: RequestPhase,
  pub downstream_status: Option<u16>,
  pub failure: Option<tokn_events::EventFailure>,
}

impl RequestCompletion {
  #[must_use]
  pub const fn new(
    outcome: RequestOutcome,
    phase: RequestPhase,
    downstream_status: Option<u16>,
    failure: Option<tokn_events::EventFailure>,
  ) -> Self {
    Self {
      outcome,
      phase,
      downstream_status,
      failure,
    }
  }
}

/// Facts that may need atomic delivery immediately before `Finished`.
///
/// The order in [`RequestTermination`] is preserved. This covers a final body
/// capture, late provider usage, attempt closure, and CONNECT closure without
/// exposing internal pipeline stages.
#[derive(Clone, Debug, Eq, PartialEq)]
#[non_exhaustive]
pub enum RequestTerminalEvent {
  BodyFinished(BodyFinished),
  AttemptUsage(AttemptUsage),
  AttemptFinished(AttemptFinished),
  ConnectClosed(ConnectClosed),
}

impl RequestTerminalEvent {
  fn into_kind(self) -> TrafficEventKind {
    match self {
      Self::BodyFinished(event) => TrafficEventKind::BodyFinished(event),
      Self::AttemptUsage(event) => TrafficEventKind::AttemptUsage(event),
      Self::AttemptFinished(event) => TrafficEventKind::AttemptFinished(event),
      Self::ConnectClosed(event) => TrafficEventKind::ConnectClosed(event),
    }
  }
}

/// One explicit, ordered terminal publication plan.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RequestTermination {
  events: Vec<RequestTerminalEvent>,
  completion: RequestCompletion,
}

impl RequestTermination {
  #[must_use]
  pub fn new(completion: RequestCompletion) -> Self {
    Self {
      events: Vec::new(),
      completion,
    }
  }

  #[must_use]
  pub fn with_event(mut self, event: RequestTerminalEvent) -> Self {
    self.events.push(event);
    self
  }

  pub fn push(&mut self, event: RequestTerminalEvent) {
    self.events.push(event);
  }

  pub fn events(&self) -> &[RequestTerminalEvent] {
    &self.events
  }

  pub const fn completion(&self) -> &RequestCompletion {
    &self.completion
  }

  fn into_kinds(self) -> (Vec<TrafficEventKind>, RequestCompletion) {
    (
      self.events.into_iter().map(RequestTerminalEvent::into_kind).collect(),
      self.completion,
    )
  }
}

/// Exactly one inbound, embedded, or CONNECT request lifecycle.
///
/// This owner is intentionally not `Clone`. Move it into the downstream body
/// or CONNECT upgrade task after publishing pre-response boundaries. Explicit
/// finish submits one atomic terminal batch; dropping it submits cancellation.
pub struct RequestLifecycle {
  publisher: Option<Publisher<GatewayEvent>>,
  terminal: Option<TerminalGuard<GatewayEvent>>,
  shared: Arc<SharedLifecycle>,
}

impl RequestLifecycle {
  pub fn request_id(&self) -> &RequestId {
    &self.shared.request_id
  }

  #[must_use]
  pub const fn is_enabled(&self) -> bool {
    self.publisher.is_some()
  }

  /// Registers a body leg before its first chunk is polled.
  ///
  /// This has no event-delivery cost. It lets a dropped zero-byte stream still
  /// produce a truthful `BodyFinished(Cancelled)` terminal observation.
  pub fn arm_body(&mut self, leg: BodyLeg) {
    self.shared.arm_body(leg);
  }

  /// Reliably publishes a stable lifecycle boundary in request order.
  ///
  /// Started, terminal Finished, and high-frequency BodyProgress have
  /// dedicated methods so they cannot accidentally violate lifecycle shape.
  pub async fn publish_boundary(&mut self, kind: TrafficEventKind) -> Result<LifecycleDelivery, BoundaryPublishError> {
    if matches!(
      kind,
      TrafficEventKind::Started(_) | TrafficEventKind::Finished(_) | TrafficEventKind::BodyProgress(_)
    ) {
      return Err(BoundaryPublishError::DedicatedKind(kind));
    }

    let (at, at_system_time) = (Instant::now(), SystemTime::now());
    let sequence = self.shared.next_sequence();
    let event = self.shared.envelope(sequence, at, at_system_time, kind.clone());
    let Some(publisher) = &self.publisher else {
      self.shared.accept(sequence, &kind);
      return Ok(LifecycleDelivery::Disabled);
    };

    publisher.publish(event).await?;
    self.shared.accept(sequence, &kind);
    Ok(LifecycleDelivery::Published)
  }

  /// Attempts one cumulative body-progress update without waiting for space.
  ///
  /// A full queue leaves the request sequence untouched and records the latest
  /// fact for the terminal batch. The caller also receives the original fact
  /// so it can explicitly coalesce future updates.
  pub fn try_publish_progress(&mut self, progress: BodyProgress) -> Result<ProgressPublication, ProgressPublishError> {
    let sequence = self.shared.next_sequence();
    let event = self.shared.envelope(
      sequence,
      Instant::now(),
      SystemTime::now(),
      TrafficEventKind::BodyProgress(progress.clone()),
    );
    let Some(terminal) = &self.terminal else {
      self.shared.accept(sequence, &TrafficEventKind::BodyProgress(progress));
      return Ok(ProgressPublication::Disabled);
    };

    match terminal.try_publish(event) {
      Ok(()) => {
        self.shared.accept(sequence, &TrafficEventKind::BodyProgress(progress));
        Ok(ProgressPublication::Published)
      }
      Err(TryPublishError::Full(_)) => {
        self.shared.coalesce_progress(&progress);
        Ok(ProgressPublication::Coalesce(progress))
      }
      Err(TryPublishError::Closed(_)) => Err(ProgressPublishError::Closed(progress)),
      Err(TryPublishError::Failed { failure, .. }) => Err(ProgressPublishError::Failed { progress, failure }),
    }
  }

  /// Atomically submits explicit terminal facts and exactly one `Finished`.
  ///
  /// Any progress coalesced because the bounded queue was full is prepended to
  /// the batch. Terminal sequence values are contiguous after the last event
  /// that was actually accepted by the hub.
  pub fn finish(mut self, termination: RequestTermination) -> Result<LifecycleDelivery, TerminalSubmitError> {
    self.shared.set_termination(termination);
    let Some(terminal) = self.terminal.take() else {
      return Ok(LifecycleDelivery::Disabled);
    };
    let shared = Arc::clone(&self.shared);
    terminal.finish_with(move |context| shared.materialize_terminal(context))?;
    Ok(LifecycleDelivery::Published)
  }
}

impl fmt::Debug for RequestLifecycle {
  fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
    formatter
      .debug_struct("RequestLifecycle")
      .field("request_id", &self.request_id())
      .field("enabled", &self.is_enabled())
      .field("armed", &self.terminal.is_some())
      .finish_non_exhaustive()
  }
}

#[derive(Clone, Copy)]
struct LifecycleClock {
  started_at: Instant,
  started_at_system_time: SystemTime,
}

impl LifecycleClock {
  fn now() -> Self {
    Self {
      started_at: Instant::now(),
      started_at_system_time: SystemTime::now(),
    }
  }
}

struct SharedLifecycle {
  request_id: RequestId,
  started_at: Instant,
  facts: Mutex<LifecycleFacts>,
}

impl SharedLifecycle {
  fn new(request_id: RequestId, started_at: Instant) -> Self {
    Self {
      request_id,
      started_at,
      facts: Mutex::new(LifecycleFacts::new()),
    }
  }

  fn lock(&self) -> MutexGuard<'_, LifecycleFacts> {
    self.facts.lock().unwrap_or_else(std::sync::PoisonError::into_inner)
  }

  fn next_sequence(&self) -> u64 {
    self.lock().next_sequence
  }

  fn accept(&self, sequence: u64, kind: &TrafficEventKind) {
    let mut facts = self.lock();
    assert_eq!(
      sequence, facts.next_sequence,
      "request lifecycle sequence changed before admission"
    );
    facts.next_sequence = facts
      .next_sequence
      .checked_add(1)
      .expect("request lifecycle sequence overflowed");
    facts.observe(kind, false);
  }

  fn coalesce_progress(&self, progress: &BodyProgress) {
    self
      .lock()
      .observe(&TrafficEventKind::BodyProgress(progress.clone()), true);
  }

  fn arm_body(&self, leg: BodyLeg) {
    self.lock().arm_body(leg);
  }

  fn set_termination(&self, termination: RequestTermination) {
    let previous = self.lock().termination.replace(termination);
    assert!(previous.is_none(), "request terminal plan was installed twice");
  }

  fn envelope(&self, sequence: u64, at: Instant, at_system_time: SystemTime, kind: TrafficEventKind) -> GatewayEvent {
    GatewayEvent::Traffic(TrafficEvent {
      request_id: self.request_id.clone(),
      sequence,
      at_unix_ms: unix_milliseconds(at_system_time),
      elapsed_ms: duration_milliseconds(at.saturating_duration_since(self.started_at)),
      kind,
    })
  }

  fn materialize_terminal(&self, context: TerminalContext) -> TerminalBatch<GatewayEvent> {
    let mut facts = self.lock();
    assert!(
      !facts.terminal_materialized,
      "request terminal batch was materialized twice"
    );
    facts.terminal_materialized = true;

    let mut kinds = facts.take_pending_progress();
    let completion = match facts.termination.take() {
      Some(termination) => {
        let (terminal_kinds, completion) = termination.into_kinds();
        kinds.extend(terminal_kinds);
        RequestCompletion {
          downstream_status: completion.downstream_status.or(facts.downstream_status),
          ..completion
        }
      }
      None => facts.cancelled(&mut kinds),
    };
    kinds.push(TrafficEventKind::Finished(RequestFinished {
      outcome: completion.outcome,
      phase: completion.phase,
      downstream_status: completion.downstream_status,
      failure: completion.failure,
      attempt_count: facts.attempt_count,
    }));

    let mut sequence = facts.next_sequence;
    let mut terminal_events = Vec::with_capacity(kinds.len());
    for kind in kinds {
      terminal_events.push(self.envelope(
        sequence,
        context.submitted_at(),
        context.submitted_at_system_time(),
        kind,
      ));
      sequence = sequence.checked_add(1).expect("request lifecycle sequence overflowed");
    }
    facts.next_sequence = sequence;
    let mut events = terminal_events.into_iter();
    let first = events.next().expect("request terminal batch always contains Finished");
    TerminalBatch::new(first, events.collect())
  }
}

struct LifecycleFacts {
  next_sequence: u64,
  phase: RequestPhase,
  downstream_status: Option<u16>,
  attempt_count: u32,
  attempts: BTreeMap<AttemptNo, AttemptFacts>,
  upstream_bodies: BTreeMap<AttemptNo, BodyProgressFacts>,
  downstream_body: Option<BodyProgressFacts>,
  connect: Option<ConnectReady>,
  termination: Option<RequestTermination>,
  terminal_materialized: bool,
}

impl LifecycleFacts {
  fn new() -> Self {
    Self {
      next_sequence: 2,
      phase: RequestPhase::Admission,
      downstream_status: None,
      attempt_count: 0,
      attempts: BTreeMap::new(),
      upstream_bodies: BTreeMap::new(),
      downstream_body: None,
      connect: None,
      termination: None,
      terminal_materialized: false,
    }
  }

  fn observe(&mut self, kind: &TrafficEventKind, pending_progress: bool) {
    match kind {
      TrafficEventKind::Started(_) => {}
      TrafficEventKind::Admitted(_) => self.phase = RequestPhase::Admission,
      TrafficEventKind::Authenticated(_) => self.phase = RequestPhase::Authentication,
      TrafficEventKind::PolicySelected(_) => self.phase = RequestPhase::Policy,
      TrafficEventKind::RequestBody(_) => self.phase = RequestPhase::RequestBody,
      TrafficEventKind::AttemptStarted(event) => {
        self.phase = RequestPhase::TargetSelection;
        self.attempt_count = self
          .attempt_count
          .checked_add(1)
          .expect("request attempt counter overflowed");
        self.attempts.insert(event.attempt, AttemptFacts::default());
      }
      TrafficEventKind::AttemptRequest(_) => self.phase = RequestPhase::UpstreamRequest,
      TrafficEventKind::AttemptResponseHead(event) => {
        self.phase = RequestPhase::UpstreamResponse;
        if let Some(attempt) = self.attempts.get_mut(&event.attempt) {
          attempt.upstream_status = Some(event.response.status);
        }
      }
      TrafficEventKind::BodyProgress(progress) => self.observe_progress(progress, pending_progress),
      TrafficEventKind::BodyFinished(event) => {
        if let Some(phase) = body_phase(event.leg) {
          self.phase = phase;
        }
        self.remove_body(event.leg);
      }
      TrafficEventKind::DownstreamResponseHead(event) => {
        self.phase = RequestPhase::DownstreamResponse;
        self.downstream_status = Some(event.status);
      }
      TrafficEventKind::AttemptUsage(_) => {}
      TrafficEventKind::AttemptFinished(event) => {
        self.phase = event.phase;
        self.attempts.remove(&event.attempt);
      }
      TrafficEventKind::ConnectReady(event) => {
        self.phase = RequestPhase::Connect;
        self.connect = Some(event.clone());
      }
      TrafficEventKind::ConnectClosed(_) => {
        self.phase = RequestPhase::Connect;
        self.connect = None;
      }
      TrafficEventKind::Finished(event) => {
        self.phase = event.phase;
        self.downstream_status = event.downstream_status.or(self.downstream_status);
      }
      _ => {}
    }
  }

  fn observe_progress(&mut self, progress: &BodyProgress, pending: bool) {
    let Some(phase) = body_phase(progress.leg) else {
      return;
    };
    self.phase = phase;
    let facts = BodyProgressFacts {
      progress: progress.clone(),
      pending,
    };
    match progress.leg {
      BodyLeg::Upstream { attempt } => {
        self.upstream_bodies.insert(attempt, facts);
      }
      BodyLeg::Downstream => self.downstream_body = Some(facts),
      _ => {}
    }
  }

  fn arm_body(&mut self, leg: BodyLeg) {
    let progress = BodyProgress {
      leg,
      bytes_seen: 0,
      chunks: 0,
    };
    match leg {
      BodyLeg::Upstream { attempt } => {
        self.upstream_bodies.entry(attempt).or_insert(BodyProgressFacts {
          progress,
          pending: false,
        });
      }
      BodyLeg::Downstream => {
        self.downstream_body.get_or_insert(BodyProgressFacts {
          progress,
          pending: false,
        });
      }
      _ => {}
    }
  }

  fn remove_body(&mut self, leg: BodyLeg) {
    match leg {
      BodyLeg::Upstream { attempt } => {
        self.upstream_bodies.remove(&attempt);
      }
      BodyLeg::Downstream => self.downstream_body = None,
      _ => {}
    }
  }

  fn take_pending_progress(&mut self) -> Vec<TrafficEventKind> {
    let mut kinds = Vec::new();
    for facts in self.upstream_bodies.values_mut() {
      if facts.pending {
        kinds.push(TrafficEventKind::BodyProgress(facts.progress.clone()));
        facts.pending = false;
      }
    }
    if let Some(facts) = &mut self.downstream_body {
      if facts.pending {
        kinds.push(TrafficEventKind::BodyProgress(facts.progress.clone()));
        facts.pending = false;
      }
    }
    kinds
  }

  fn cancelled(&self, kinds: &mut Vec<TrafficEventKind>) -> RequestCompletion {
    for (attempt, facts) in &self.upstream_bodies {
      kinds.push(TrafficEventKind::BodyFinished(BodyFinished {
        leg: BodyLeg::Upstream { attempt: *attempt },
        capture: BodyCapture::Omitted {
          reason: CaptureOmission::Unavailable,
          bytes_seen: facts.progress.bytes_seen,
        },
        result: BodyResult::Cancelled,
      }));
    }
    if let Some(facts) = &self.downstream_body {
      kinds.push(TrafficEventKind::BodyFinished(BodyFinished {
        leg: BodyLeg::Downstream,
        capture: BodyCapture::Omitted {
          reason: CaptureOmission::Unavailable,
          bytes_seen: facts.progress.bytes_seen,
        },
        result: BodyResult::Cancelled,
      }));
    }
    for (attempt, facts) in &self.attempts {
      kinds.push(TrafficEventKind::AttemptFinished(AttemptFinished {
        attempt: *attempt,
        outcome: AttemptOutcome::Cancelled,
        phase: self.phase,
        upstream_status: facts.upstream_status,
        failure: None,
        retry: None,
      }));
    }
    if let Some(connect) = &self.connect {
      kinds.push(TrafficEventKind::ConnectClosed(ConnectClosed {
        action: connect.action,
        client_to_upstream_bytes: None,
        upstream_to_client_bytes: None,
        result: BodyResult::Cancelled,
      }));
    }
    RequestCompletion::new(RequestOutcome::Cancelled, self.phase, self.downstream_status, None)
  }
}

#[derive(Default)]
struct AttemptFacts {
  upstream_status: Option<u16>,
}

struct BodyProgressFacts {
  progress: BodyProgress,
  pending: bool,
}

const fn body_phase(leg: BodyLeg) -> Option<RequestPhase> {
  match leg {
    BodyLeg::Upstream { .. } => Some(RequestPhase::UpstreamResponse),
    BodyLeg::Downstream => Some(RequestPhase::DownstreamResponse),
    _ => None,
  }
}

fn gateway_event_kind(event: GatewayEvent) -> TrafficEventKind {
  match event {
    GatewayEvent::Traffic(event) => event.kind,
    _ => unreachable!("request lifecycle only constructs traffic events"),
  }
}

fn duration_milliseconds(duration: Duration) -> u64 {
  u64::try_from(duration.as_millis()).unwrap_or(u64::MAX)
}

fn unix_milliseconds(time: SystemTime) -> i64 {
  let milliseconds = match time.duration_since(UNIX_EPOCH) {
    Ok(duration) => i128::try_from(duration.as_millis()).unwrap_or(i128::MAX),
    Err(error) => -i128::try_from(error.duration().as_millis()).unwrap_or(i128::MAX),
  };
  milliseconds.clamp(i128::from(i64::MIN), i128::from(i64::MAX)) as i64
}

#[cfg(test)]
mod tests {
  use super::*;
  use std::sync::mpsc;
  use std::time::Duration;
  use tokn_events::{
    CapturedHeaders, CapturedUri, ConsumerResult, Correlation, EventConsumer, EventFailure, EventSeq, HubBuilder,
    IngressKind, RequestAdmitted, RequestSource,
  };

  struct CaptureConsumer {
    events: Arc<Mutex<Vec<GatewayEvent>>>,
  }

  impl EventConsumer<GatewayEvent> for CaptureConsumer {
    fn name(&self) -> &str {
      "request-lifecycle-test"
    }

    fn handle(&mut self, _sequence: EventSeq, event: &GatewayEvent) -> ConsumerResult {
      self.events.lock().unwrap().push(event.clone());
      Ok(())
    }
  }

  fn started() -> RequestStarted {
    RequestStarted {
      source: RequestSource::Listener {
        listener_id: "main".into(),
        ingress: IngressKind::LlmApi,
        local_addr: None,
        peer_addr: None,
      },
      http_version: Some("HTTP/1.1".into()),
      method: "POST".into(),
      target: CapturedUri::exact("/v1/responses"),
      headers: CapturedHeaders::default(),
      body_present: true,
      correlation: Correlation::default(),
    }
  }

  fn traffic(events: &Arc<Mutex<Vec<GatewayEvent>>>) -> Vec<TrafficEvent> {
    events
      .lock()
      .unwrap()
      .iter()
      .filter_map(|event| match event {
        GatewayEvent::Traffic(event) => Some(event.clone()),
        _ => None,
      })
      .collect()
  }

  #[tokio::test]
  async fn generated_ids_are_gateway_owned_and_unique() {
    let first = generate_request_id();
    let second = generate_request_id();

    assert_ne!(first, second);
    assert!(uuid::Uuid::parse_str(first.as_str()).is_ok());
    assert!(uuid::Uuid::parse_str(second.as_str()).is_ok());
  }

  #[tokio::test]
  async fn disabled_mode_preserves_the_complete_caller_api() {
    let emitter = RequestLifecycleEmitter::disabled();
    let mut lifecycle = emitter.begin(started()).await.unwrap();

    assert!(!lifecycle.is_enabled());
    assert_eq!(
      lifecycle
        .publish_boundary(TrafficEventKind::Admitted(RequestAdmitted::Http {
          scheme: "http".into(),
          authority: "localhost".into(),
          path_and_query: CapturedUri::exact("/v1/responses"),
          operation: Some("responses".into()),
        }))
        .await
        .unwrap(),
      LifecycleDelivery::Disabled
    );
    assert_eq!(
      lifecycle
        .try_publish_progress(BodyProgress {
          leg: BodyLeg::Downstream,
          bytes_seen: 12,
          chunks: 1,
        })
        .unwrap(),
      ProgressPublication::Disabled
    );
    assert_eq!(
      lifecycle
        .finish(RequestTermination::new(RequestCompletion::new(
          RequestOutcome::Delivered,
          RequestPhase::Complete,
          Some(200),
          None,
        )))
        .unwrap(),
      LifecycleDelivery::Disabled
    );
  }

  #[tokio::test]
  async fn started_boundaries_and_terminal_batch_are_contiguous() {
    let events = Arc::new(Mutex::new(Vec::new()));
    let (publisher, hub) = HubBuilder::new()
      .consumer(CaptureConsumer {
        events: Arc::clone(&events),
      })
      .start()
      .unwrap();
    let emitter = RequestLifecycleEmitter::new(publisher);
    let request_id = RequestId::new("gateway-id").unwrap();
    let mut lifecycle = emitter.begin_with_id(request_id.clone(), started()).await.unwrap();
    lifecycle
      .publish_boundary(TrafficEventKind::Admitted(RequestAdmitted::Http {
        scheme: "http".into(),
        authority: "localhost".into(),
        path_and_query: CapturedUri::exact("/v1/responses"),
        operation: None,
      }))
      .await
      .unwrap();
    lifecycle
      .finish(RequestTermination::new(RequestCompletion::new(
        RequestOutcome::Rejected,
        RequestPhase::RequestBody,
        Some(400),
        None,
      )))
      .unwrap();
    let stats = hub.shutdown().await.unwrap();

    assert_eq!(stats.delivered, 3);
    let traffic = traffic(&events);
    assert_eq!(
      traffic.iter().map(|event| event.sequence).collect::<Vec<_>>(),
      vec![1, 2, 3]
    );
    assert!(matches!(traffic[0].kind, TrafficEventKind::Started(_)));
    assert!(matches!(traffic[1].kind, TrafficEventKind::Admitted(_)));
    let TrafficEventKind::Finished(finished) = &traffic[2].kind else {
      panic!("expected Finished")
    };
    assert_eq!(finished.attempt_count, 0);
    assert_eq!(traffic[0].request_id, request_id);
  }

  #[tokio::test]
  async fn body_error_and_failure_finish_in_one_terminal_batch() {
    let events = Arc::new(Mutex::new(Vec::new()));
    let (publisher, hub) = HubBuilder::new()
      .consumer(CaptureConsumer {
        events: Arc::clone(&events),
      })
      .start()
      .unwrap();
    let emitter = RequestLifecycleEmitter::new(publisher);
    let lifecycle = emitter.begin(started()).await.unwrap();
    let failure = EventFailure {
      code: "downstream_body_read".into(),
      message: "client response body failed".into(),
    };
    lifecycle
      .finish(
        RequestTermination::new(RequestCompletion::new(
          RequestOutcome::Failed,
          RequestPhase::DownstreamResponse,
          Some(502),
          Some(failure.clone()),
        ))
        .with_event(RequestTerminalEvent::BodyFinished(BodyFinished {
          leg: BodyLeg::Downstream,
          capture: BodyCapture::Omitted {
            reason: CaptureOmission::Unavailable,
            bytes_seen: 9,
          },
          result: BodyResult::Failed(failure.clone()),
        })),
      )
      .unwrap();
    hub.shutdown().await.unwrap();

    let traffic = traffic(&events);
    assert_eq!(
      traffic.iter().map(|event| event.sequence).collect::<Vec<_>>(),
      vec![1, 2, 3]
    );
    assert!(matches!(
      &traffic[1].kind,
      TrafficEventKind::BodyFinished(BodyFinished {
        result: BodyResult::Failed(observed),
        ..
      }) if observed == &failure
    ));
    assert!(matches!(
      &traffic[2].kind,
      TrafficEventKind::Finished(RequestFinished {
        outcome: RequestOutcome::Failed,
        failure: Some(observed),
        attempt_count: 0,
        ..
      }) if observed == &failure
    ));
  }

  struct BlockingConsumer {
    events: Arc<Mutex<Vec<GatewayEvent>>>,
    entered: mpsc::Sender<()>,
    release: mpsc::Receiver<()>,
    first: bool,
  }

  impl EventConsumer<GatewayEvent> for BlockingConsumer {
    fn name(&self) -> &str {
      "blocking-request-lifecycle-test"
    }

    fn handle(&mut self, _sequence: EventSeq, event: &GatewayEvent) -> ConsumerResult {
      self.events.lock().unwrap().push(event.clone());
      if self.first {
        self.first = false;
        self.entered.send(()).unwrap();
        self.release.recv().unwrap();
      }
      Ok(())
    }
  }

  #[tokio::test(flavor = "multi_thread", worker_threads = 2)]
  async fn full_progress_is_coalesced_without_consuming_a_sequence() {
    let events = Arc::new(Mutex::new(Vec::new()));
    let (entered_tx, entered_rx) = mpsc::channel();
    let (release_tx, release_rx) = mpsc::channel();
    let (publisher, hub) = HubBuilder::new()
      .capacity(1)
      .consumer(BlockingConsumer {
        events: Arc::clone(&events),
        entered: entered_tx,
        release: release_rx,
        first: true,
      })
      .start()
      .unwrap();
    let emitter = RequestLifecycleEmitter::new(publisher);
    let mut lifecycle = emitter.begin(started()).await.unwrap();
    entered_rx.recv_timeout(Duration::from_secs(1)).unwrap();
    lifecycle
      .publish_boundary(TrafficEventKind::Admitted(RequestAdmitted::Connect {
        authority: "example.com:443".into(),
      }))
      .await
      .unwrap();
    let progress = BodyProgress {
      leg: BodyLeg::Downstream,
      bytes_seen: 27,
      chunks: 2,
    };
    assert_eq!(
      lifecycle.try_publish_progress(progress.clone()).unwrap(),
      ProgressPublication::Coalesce(progress.clone())
    );
    release_tx.send(()).unwrap();

    lifecycle
      .finish(
        RequestTermination::new(RequestCompletion::new(
          RequestOutcome::Cancelled,
          RequestPhase::DownstreamResponse,
          None,
          None,
        ))
        .with_event(RequestTerminalEvent::BodyFinished(BodyFinished {
          leg: BodyLeg::Downstream,
          capture: BodyCapture::Omitted {
            reason: CaptureOmission::Unavailable,
            bytes_seen: 27,
          },
          result: BodyResult::Cancelled,
        })),
      )
      .unwrap();
    hub.shutdown().await.unwrap();

    let traffic = traffic(&events);
    assert_eq!(
      traffic.iter().map(|event| event.sequence).collect::<Vec<_>>(),
      vec![1, 2, 3, 4, 5]
    );
    assert!(matches!(traffic[2].kind, TrafficEventKind::BodyProgress(_)));
    assert!(matches!(traffic[3].kind, TrafficEventKind::BodyFinished(_)));
    assert!(matches!(traffic[4].kind, TrafficEventKind::Finished(_)));
  }

  #[tokio::test]
  async fn dropping_a_live_body_closes_body_attempt_and_request_once() {
    let events = Arc::new(Mutex::new(Vec::new()));
    let (publisher, hub) = HubBuilder::new()
      .consumer(CaptureConsumer {
        events: Arc::clone(&events),
      })
      .start()
      .unwrap();
    let emitter = RequestLifecycleEmitter::new(publisher);
    let mut lifecycle = emitter.begin(started()).await.unwrap();
    lifecycle
      .publish_boundary(TrafficEventKind::AttemptStarted(tokn_events::AttemptStarted {
        attempt: AttemptNo::FIRST,
        target: tokn_events::TargetSelection {
          family: tokn_events::HttpFamily::Managed,
          account_id: None,
          provider_id: None,
          upstream_id: None,
          requested_model: None,
          upstream_model: None,
          requested_operation: None,
          upstream_operation: None,
        },
      }))
      .await
      .unwrap();
    lifecycle.arm_body(BodyLeg::Upstream {
      attempt: AttemptNo::FIRST,
    });
    drop(lifecycle);
    hub.shutdown().await.unwrap();

    let traffic = traffic(&events);
    assert_eq!(
      traffic.iter().map(|event| event.sequence).collect::<Vec<_>>(),
      vec![1, 2, 3, 4, 5]
    );
    assert!(matches!(
      traffic[2].kind,
      TrafficEventKind::BodyFinished(BodyFinished {
        capture: BodyCapture::Omitted { bytes_seen: 0, .. },
        result: BodyResult::Cancelled,
        ..
      })
    ));
    assert!(matches!(
      traffic[3].kind,
      TrafficEventKind::AttemptFinished(AttemptFinished {
        outcome: AttemptOutcome::Cancelled,
        ..
      })
    ));
    let TrafficEventKind::Finished(finished) = &traffic[4].kind else {
      panic!("expected Finished")
    };
    assert_eq!(finished.outcome, RequestOutcome::Cancelled);
    assert_eq!(finished.attempt_count, 1);
  }

  #[tokio::test]
  async fn dropping_connect_closes_the_observed_exchange_without_inventing_byte_counts() {
    let events = Arc::new(Mutex::new(Vec::new()));
    let (publisher, hub) = HubBuilder::new()
      .consumer(CaptureConsumer {
        events: Arc::clone(&events),
      })
      .start()
      .unwrap();
    let emitter = RequestLifecycleEmitter::new(publisher);
    let mut lifecycle = emitter.begin(started()).await.unwrap();
    lifecycle
      .publish_boundary(TrafficEventKind::ConnectReady(ConnectReady {
        action: tokn_events::ConnectAction::Tunnel,
        authority: "example.com:443".into(),
      }))
      .await
      .unwrap();
    drop(lifecycle);
    hub.shutdown().await.unwrap();

    let traffic = traffic(&events);
    assert_eq!(
      traffic.iter().map(|event| event.sequence).collect::<Vec<_>>(),
      vec![1, 2, 3, 4]
    );
    assert!(matches!(
      traffic[2].kind,
      TrafficEventKind::ConnectClosed(ConnectClosed {
        action: tokn_events::ConnectAction::Tunnel,
        client_to_upstream_bytes: None,
        upstream_to_client_bytes: None,
        result: BodyResult::Cancelled,
      })
    ));
    assert!(matches!(
      traffic[3].kind,
      TrafficEventKind::Finished(RequestFinished {
        outcome: RequestOutcome::Cancelled,
        phase: RequestPhase::Connect,
        ..
      })
    ));
  }
}
